services:
  docker-brave:
    image: docker.io/devloic/docker-brave
    privileged: true
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "./sharedwithhost:/config/sharedwithhost"
    environment:
      - WEB_AUDIO=1
