services:
  docker-brave:
    image: ghcr.io/devloic/podman-brave:main
    privileged: true
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "./sharedwithhost:/config/sharedwithhost"
      - "/dev/snd:/dev/snd"
    environment:
      - WEB_AUDIO=1
